blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/allonsy-studio/dashly/discussions
    about: Not a bug or feature request? Start a discussion instead.
