name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node LTS version
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: Install Node dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn ci:test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node LTS version
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: Install Node dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
